import { EventEmitter } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import {ILogin, ILoginResponse} from '../app.interface';
export abstract class DataService {
    public abstract loginUser( obj: ILogin): Observable<ILoginResponse>;
    public abstract getCountriesList(): Observable<any>;
    public abstract getEmployeeDetails( id: string ): Observable<any>;
    public abstract uploadProfileImage( obj ): Observable<any>;
    public abstract uploadProfileResume( obj ): Observable<any>;
    public abstract getProfessionalDetails( id ): Observable<any>;
    public abstract getDomainDetails( id ): Observable<any>;
    public abstract getSkillCategories(): Observable<any>;
    public abstract getSkillsByCategory(id): Observable<any>;
    public abstract getMasterDomainDetails(): Observable<any>;
    public abstract getCertificationTechnologies(): Observable<any>;
    public abstract getProjectDetails( id ): Observable<any>;
    public abstract getSubDomainDetails( id ): Observable<any>;
    public abstract getChildDomainDetails( dId, sId ): Observable<any>;
    public abstract getThemes(): Observable<any>;
    public abstract updateTheme( paramObj ): Observable<any>;
    public abstract saveContactAndExpDetails( paramObj ): Observable<any>;
    public abstract profilePercentage: EventEmitter<number>;
    public abstract addUpdateSkill(obj, value, lastUpdated): Observable<any>;
    public abstract addUpdateDomain(obj, value, lastUpdated): Observable<any>;
    public abstract addUpdateVisa(obj): Observable<any>;
    public abstract addUpdatePassport(obj): Observable<any>;
    public abstract addUpdateCertification(obj): Observable<any>;
    public abstract addUpdateProject(obj): Observable<any>;
    public abstract addUpdateEmployee(obj): Observable<any>;
    public abstract addUpdateBuDtls(obj): Observable<any>;
    public abstract deleteDomain(obj, value, lastUpdated): Observable<any>;
    public abstract deleteProject(obj): Observable<any>;
    public abstract deleteSkill(obj, value, lastUpdated): Observable<any>;
    public abstract deleteVisa(obj): Observable<any>;
    public abstract deletePassport(obj): Observable<any>; 
    public abstract deleteCertification(obj): Observable<any>;
    public abstract getVisaDetails(id) : Observable<any>;
    public abstract getCertificationNamesInstitutes(id) : Observable<any>;
}